x-log-volume: &log-volume
  logs:/var/log

services:
  # nepenthes:
  #   build: ./nepenthes
  #   ports:
  #     - "8003:8000"

  paste:
    build: ./paste
    ports:
      - "8004:8000"
    depends_on:
      - redis
    environment:
      LOG_FILE: /var/log/paste.log
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
    - *log-volume

  cdn:
    build: ./cdn
    ports:
      - "8007:8000"
    volumes:
      - cdn:/app/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - portainer_network

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - registry:/var/lib/registry
      - ${SERV_CONFIG_DIR}/registry.yml:/etc/docker/registry/config.yml
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry realm" 
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    networks:
      - registry_network

volumes:
  cdn:
  logs:
    external: true
  postgres:
  registry:
  portainer_data:

networks:
  portainer_network:
    driver: bridge
    name: portainer_network
  registry_network:
    driver: bridge
    name: registry_network
