x-log-volume: &log-volume
  logs:/var/log

services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ${SERV_CONFIG_DIR}/loki.yaml:/mnt/config/loki.yaml
      - loki:/mnt/loki
    command: -config.file=/mnt/config/loki.yaml
    deploy:
      replicas: 1

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - *log-volume
      - ${SERV_CONFIG_DIR}/promtail.yaml:/mnt/config/promtail.yaml
    command: -config.file=/mnt/config/promtail.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD:
    depends_on:
      - loki
    volumes:
      - grafana:/var/lib/grafana
      - other-data:/mnt/data
      - ${SERV_CONFIG_DIR}/grafana.ini:/etc/grafana/grafana.ini
    deploy:
      replicas: 1

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: "host"
    ports:
      - "9100:9100"
    command:
      - --path.rootfs=/host
      - --web.listen-address=:9100
      - --web.telemetry-path=/metrics
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - ${SERV_CONFIG_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  data_http:
    image: python:3.12-slim
    container_name: data_http
    restart: unless-stopped
    ports:
      - "1000:1000"
    volumes:
      - other-data:/data
    command: python3 -m http.server 1000 --directory /data

volumes:
  grafana:
  prometheus:
  loki:
  logs:
    external: true
  other-data:
    external: true
