server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: archive
  static_configs:
  - targets:
      - localhost
    labels:
      job: archive
      __path__: /var/log/archive.log

- job_name: blog
  static_configs:
  - targets:
      - localhost
    labels:
      job: blog
      __path__: /var/log/blog.log
