footer:
  poweredBy: '<img src="https://img.shields.io/badge/Astro-20232A?style=for-the-badge&logo=Astro&logoColor=BC52EE" alt="Astro"/>'
  madeWith: '<img src="https://img.shields.io/badge/❤️-red?style=for-the-badge" alt="love">'
  inspiredBy: '<a href="https://github.com/cyteon/the-watcher">The Watcher</a>'
  license: >
    <a href="http://www.wtfpl.net/">
      <img
      src="http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-badge-4.png"
      width="80"
      height="15"
      alt="WTFPL"/>
    </a>

degradedMultiplier: 2
uptimeCheckInterval: 30
servicesCacheTTL: 60

services:
  dwmun:
    name: 'DWMUN25'
    url: 'https://dwmun.arson.dev'
    description: 'The official website of DWMUN25'
    recovery: 'pm2 restart dwmun25'

